### ISSUE TITLE
esrf nexus to cbf

### ISSUE THREAD

**Issue by geocarly** [biochem-fan/eiger2cbf#10]
Hello,
in a view of using eiger2cbf ta ID11 for the new Eiger2-4M, I am trying to learn eiger2cbf with a dataset form id30a (which perhaps should be working.) 
When I run the command : eiger2cbf id30_eiger_0003.h5 1:1000 out i get the error at the end of this message.
My question is: is it because I need to modify the eiger2cbf.c in the section main with the right values?
Or can I add these info as arguments?
Is there a detailed manual?
Thanks a lot for your help!
Carlotta

EIGER HDF5 to CBF converter (version 160415)
 written by Takanori Nakane
 see https://github.com/biochem-fan/eiger2cbf for details.

HDF5-DIAG: Error detected in HDF5 (1.8.13) thread 140442264835840:
  #000: ../../../src/H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
Going to convert frame 1 to 1000.
Metadata in HDF5:
 /entry/instrument/detector/description = 
 /entry/instrument/detector/detector_number = 
 /entry/instrument/detector/detectorSpecific/software_version = 
 WARNING: /entry/instrument/detector/bit_depth_image is not avaialble. We assume 16 bit.
  /entry/instrument/detector/detectorSpecific/saturation_value not present. Trying another place.
  /entry/instrument/detector/detectorSpecific/countrate_correction_count_cutoff not present. Trying another place.
  /entry/instrument/detector/detectorSpecific/detectorModule_000/countrate_correction_count_cutoff not present.
  As a last resort, we will put an arbitrary large number (65534) in the header.
  You might want to change the OVERLOAD setting in your subsequent processing.
 /entry/instrument/detector/sensor_thickness is not avaialble. We assume it is 450.000000 um
 /entry/instrument/detector/detectorSpecific/{x,y}_pixels_in_detector = (-1, -1) (px)
 /entry/instrument/detector/beam_center_{x,y} = (-1, -1) (px)
 /entry/instrument/detector/count_time = -1.000000 (sec)
 /entry/instrument/detector/frame_time = -1.000000 (sec)
 /entry/instrument/detector/x_pixel_size = -1.000000 (m)
  /entry/instrument/detector/distance not present. Trying another place.
  /entry/instrument/detector/detector_distance not present.
 WARNING: detector distance was not defined! "Detector distance" field in the output is set to -1.
  /entry/sample/beam/incident_wavelength not present. Trying another place.
  /entry/instrument/beam/wavelength not present. Trying another place.
  /entry/instrument/monochromator/wavelength not present. Trying another place.
  /entry/instrument/beam/incident_wavelength not present.
 WARNING: wavelength was not defined! "Wavelength" field in the output is set to -1.
 WARNING: oscillation width was not defined. "Start_angle" field in the output is set to 0!

**Comment by biochem-fan** [comment]
EIGER2 writes metadata in a different way than EIGER. This is why the program is failing.

Now that most data processing programs natively read HDF5 files, I am less inclined to update the program. Why do you need conversion to CBF?

**Comment by geocarly** [comment]
Hi,
I would like to use the cbf file in crysalis.
But if there is another way to get around this issue I am willing to learn!
Best,

Carlotta

**Comment by biochem-fan** [comment]
I am afraid to say that I don't want to spend time for the sake of a non-open source commercial program. I would use DIALS for data processing (including small molecules).

If you are keen to use CrysAlis and the image header is not important, you might be able to write a CBF using `dials.convert_to_cbf`.

**Comment by geocarly** [comment]
Hi,
I can see your point.
I will try to get familiar with Dials then in the next days and give it a go.
For now, thanks for your answers!

Best,

Carlotta
