### ISSUE TITLE
Problem using eiger2cbf

### ISSUE THREAD

**Issue by MarjanH** [biochem-fan/eiger2cbf#4]
Hi, I am trying to convert some data using your program and following is the outcome. When i import the output to imosflm all the output are empty and I cannot process them. Can you please let me know what I am doing wrong?  these are the data we collect from eiger , esrf.  I installed all the dependencies. Ireally appreciate if you could help me .

Many thanks. 

./eiger2cbf  W_50_570_master.h5 1:112 W_50
EIGER HDF5 to CBF converter (version 160415)
 written by Takanori Nakane
 see https://github.com/biochem-fan/eiger2cbf for details.

Going to convert frame 1 to 112.
Metadata in HDF5:
 /entry/instrument/detector/description = Dectris Eiger 4M
 /entry/instrument/detector/detector_number = E-08-0106
 /entry/instrument/detector/detectorSpecific/software_version = 1.6.1
 /entry/instrument/detector/bit_depth_image = 16
  /entry/instrument/detector/detectorSpecific/saturation_value not present. Trying another place.
 /entry/instrument/detector/detectorSpecific/countrate_correction_count_cutoff = 38086
 /entry/instrument/detector/sensor_thickness = 449999.988079 (um)
 /entry/instrument/detector/detectorSpecific/{x,y}_pixels_in_detector = (2070, 2167) (px)
 /entry/instrument/detector/beam_center_{x,y} = (0, 0) (px)
 /entry/instrument/detector/count_time = 0.015000 (sec)
 /entry/instrument/detector/frame_time = 0.015010 (sec)
 /entry/instrument/detector/x_pixel_size = 0.000075 (m)
  /entry/instrument/detector/distance not present. Trying another place.
  /entry/instrument/detector/detector_distance not present.
 WARNING: detector distance was not defined! "Detector distance" field in the output is set to -1.
  /entry/sample/beam/incident_wavelength not present. Trying another place.
  /entry/instrument/beam/wavelength not present. Trying another place.
  /entry/instrument/monochromator/wavelength not present. Trying another place.
 /entry/instrument/beam/incident_wavelength = 0.953725 (A)
 WARNING: oscillation width was not defined. "Start_angle" field in the output is set to 0!

This dataset starts from data_000001.
The number of images per data block is 200.

File analysis completed.

Converting frame 1 (1 / 112)
 /entry/sample/goniometer/omega[1] = 0.000 (1-indexed)
Converting frame 2 (2 / 112)
 /entry/sample/goniometer/omega[2] = 0.000 (1-indexed)
Converting frame 3 (3 / 112)
...
Converting frame 111 (111 / 112)
 /entry/sample/goniometer/omega[111] = 0.000 (1-indexed)
Converting frame 112 (112 / 112)
 /entry/sample/goniometer/omega[112] = 0.000 (1-indexed)

All done!

**Comment by biochem-fan** [comment]
First, please make sure that the output images are really empty, for example by adxv.

Next, the header of your dataset does not look right. Where and when did you collect this?
This should be reported to the beamline scientist. You have to manually set
the beam centre, detector distance and oscillation angle to iMOSFLM.

**Comment by MarjanH** [comment]
Thanks a lot for quick answer.
