### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by MarjanH** [biochem-fan/eiger2cbf#5]
Hi
While installing eiger2cbf I get the following warning, but CBFLib  'make tests' gives no error. So I assumed that eiger2cbf would work. Could you please let me know if this warning matters or if the imported h5 files have problem? Thanks a lot for your time and help.

best regards

root@alipc:/home/ali/Downloads/eiger2cbf-master# make
/usr/bin/gcc -O3 -std=c99 -o eiger2cbf -g \
-I/home/ali/Downloads/CBFlib-0.9.5.17/include \
-L/home/ali/Downloads/CBFlib-0.9.5.17/lib -Ilz4 \
eiger2cbf.c \
lz4/lz4.c lz4/h5zlz4.c \
bitshuffle/bshuf_h5filter.c \
bitshuffle/bshuf_h5plugin.c \
bitshuffle/bitshuffle.c \
/home/ali/Downloads/CBFlib-0.9.5.17/lib/libhdf5_hl.a \
/home/ali/Downloads/CBFlib-0.9.5.17/lib/libhdf5.a \
-lcbf -lm -lpthread -lz -ldl
bitshuffle/bitshuffle.c: In function ‘bshuf_decompress_lz4_block’:
bitshuffle/bitshuffle.c:1311:14: warning: implicit declaration of function ‘LZ4_decompress_fast’ [-Wimplicit-function-declaration]
     nbytes = LZ4_decompress_fast((char*) in + 4, tmp_buf, size * elem_size);

**Comment by biochem-fan** [comment]
Sorry, I didn't notice this thread. Yes, you can safely ignore the warning.

**Comment by MarjanH** [comment]
Thanks , yes I realized that. Thanks.
